# Generated by Django 4.1.1 on 2022-09-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_submission_score_alter_submission_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('c', 'C'), ('c++', 'C++'), ('python', 'Python')], max_length=10, null=True),
        ),
    ]
