# Generated by Django 4.1.1 on 2022-10-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_submission_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='memory_limit',
            field=models.IntegerField(default=256, null=True),
        ),
    ]
