# Generated by Django 4.1.1 on 2022-10-26 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_question_memory_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='cid',
        ),
    ]
